//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTier
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CallMonitorModelEntities : DbContext
    {
        public CallMonitorModelEntities()
            : base("name=CallMonitorModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CallEntity> CALL { get; set; }
        public DbSet<CallStateEntity> CALL_STATE { get; set; }
        public DbSet<CustomerEntity> CUSTOMER { get; set; }
        public DbSet<CustomerBonusEntity> CUSTOMER_BONUS { get; set; }
        public DbSet<CustomerPhoneEntity> CUSTOMER_PHONE { get; set; }
        public DbSet<MinimunRechargeEntity> MINIMUN_RECHARGE { get; set; }
        public DbSet<PriceEntity> PRICE { get; set; }
        public DbSet<PromotionEntity> PROMOTION { get; set; }
        public DbSet<PromotionValueTypeEntity> PROMOTION_VALUETYPE { get; set; }
        public DbSet<RechargeEntity> RECHARGE { get; set; }
        public DbSet<RechargeStateEntity> RECHARGE_STATE { get; set; }
    }
}
