//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTier
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallEntity
    {
        public int PhoneCall_Id { get; set; }
        public int Customer_id { get; set; }
        public string Phone_Number { get; set; }
        public string Destination_Number { get; set; }
        public System.DateTime Initial_DateTime { get; set; }
        public System.DateTime Final_DateTime { get; set; }
        public decimal Call_Duration { get; set; }
        public decimal Call_Cost { get; set; }
        public int Call_State { get; set; }
    
        public virtual CallStateEntity CALL_STATE1 { get; set; }
        public virtual CustomerEntity CUSTOMER { get; set; }
    }
}
