//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTier
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerEntity
    {
        public CustomerEntity()
        {
            this.CALL = new HashSet<CallEntity>();
            this.CUSTOMER_BONUS = new HashSet<CustomerBonusEntity>();
            this.CUSTOMER_PHONE = new HashSet<CustomerPhoneEntity>();
            this.RECHARGE = new HashSet<RechargeEntity>();
        }
    
        public int Id_Type { get; set; }
        public int Id { get; set; }
        public string First_Name { get; set; }
        public string Second_Name { get; set; }
        public string Last_Name { get; set; }
        public string Phone_Number { get; set; }
    
        public virtual ICollection<CallEntity> CALL { get; set; }
        public virtual ICollection<CustomerBonusEntity> CUSTOMER_BONUS { get; set; }
        public virtual ICollection<CustomerPhoneEntity> CUSTOMER_PHONE { get; set; }
        public virtual ICollection<RechargeEntity> RECHARGE { get; set; }
    }
}
