//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTier
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionEntity
    {
        public PromotionEntity()
        {
            this.CUSTOMER_BONUS = new HashSet<CustomerBonusEntity>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public int Value { get; set; }
        public int Value_Type { get; set; }
    
        public virtual ICollection<CustomerBonusEntity> CUSTOMER_BONUS { get; set; }
        public virtual PromotionValueTypeEntity PROMOTION_VALUETYPE { get; set; }
    }
}
