//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTier
{
    using System;
    using System.Collections.Generic;
    
    public partial class RechargeEntity
    {
        public long Recharge_Code { get; set; }
        public int Customer_Id { get; set; }
        public string Phone_Number { get; set; }
        public decimal Recharge_value { get; set; }
        public System.DateTime Recharge_Date { get; set; }
        public int Recharge_State { get; set; }
    
        public virtual CustomerEntity CUSTOMER { get; set; }
        public virtual RechargeStateEntity RECHARGE_STATE1 { get; set; }
    }
}
